language: go
sudo: false

go:
  - 1.15
  - 1.16
  - tip

env:

before_install:
  - export PATH=$PATH:$GOPATH/bin
  
install:
  - go get -t -v ./...

script:
  - go vet ./...
  - diff -u <(echo -n) <(gofmt -d -s .)

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - go: tip
